[project]
name = "test-classic"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Ivann KAMDEM", email = "kapoivha@gmail.com" }
]
requires-python = ">=3.12.12"
dependencies = []

[project.scripts]
test-classic = "test_classic:main"

[build-system]
requires = ["uv_build>=0.9.21,<0.10.0"]
build-backend = "uv_build"
